# 1. Əsas obraz olaraq ən son Ubuntu versiyasını seçirik
FROM ubuntu:latest

# 2. APT-ı yeniləyirik və proqramları təkmilləşdiririk
RUN apt-get update && apt-get upgrade -y

# 3. Konteyner işə düşəndə nə etməli olduğunu deyirik
CMD ["echo", "Hello, World!"]
